# .bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='\[\e[38;5;142m\]\u@\h\[\e[0m\]:'

neofetch

export PATH=$PATH:/home/t410/.millennium/ext/bin
